#!/usr/bin/env bash
# lock_requirements.sh — pin the cloud images + CI to the EXACT package versions of the working
# local .venv (parity: "runs on Cloud Run like it does on localhost").
#
#   scripts/lock_requirements.sh        # → requirements.lock   (commit it)
#
# Without a lock, `docker build` resolves the newest versions at build time; on 2026-10-06 that
# meant google-adk 2.11 vs 2.2 locally, mediapipe 1.1 vs 0.10, opencv 5 vs 4 — and Live Voice
# (BIDI) broke in production while working locally.
# Excluded: torch/torchvision (installed per variant from the CPU or CUDA index, pinned in the
# Dockerfile), this package itself, and yt-dlp (kept current — YouTube breaks old versions).
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
{
  echo "# Generated by scripts/lock_requirements.sh from the working local .venv — do not edit."
  uv pip freeze --python .venv/bin/python \
    | grep -vE '^-e |^(torch|torchvision)==|^yt-dlp'
  echo "yt-dlp"
} > requirements.lock
echo "✓ requirements.lock ($(grep -c '==' requirements.lock) pinned)"
